const backend = {
  api: { unauthorized: 'Innlogging kreves.', forbidden: 'Du har ikke tilgang.', invalidRequest: 'Ugyldig forespørsel.', invalidJson: 'Ugyldig JSON.', serverError: 'Forespørselen kunne ikke fullføres. Prøv igjen.', tooManyRequests: 'For mange forespørsler. Vent litt og prøv igjen.' },
  members: { attempts: 'For mange forsøk. Vent litt før du prøver igjen.', genericAccess: 'Hvis opplysningen samsvarer med registeret, sender vi en sikker lenke til registrert hoved-e-post.', unavailableWait: 'Tjenesten er midlertidig utilgjengelig. Vent litt og prøv igjen.', changes: 'For mange endringer. Vent litt og prøv igjen.', ownershipSent: 'Eierskiftet er sendt til behandling.', emailSent: 'En bekreftelseslenke er sendt til den nåværende hoved-e-postadressen.', invalidAction: 'Ugyldig handling.', updated: 'Opplysningene er oppdatert.', unavailable: 'Tjenesten er midlertidig utilgjengelig. Prøv igjen senere.', invalidAccess: 'Tilgangen er ugyldig eller utløpt.', ownershipPending: 'Det finnes allerede en eierskifteforespørsel til behandling.', emailFlow: 'Hoved-e-post må endres med den separate bekreftelsesflyten.', deliveryUnavailable: 'Vi kan ikke sende bekreftelsen til den registrerte adressen. Kontakt Turufjell Vel.', checkContact: 'Kontroller kontaktopplysningene.', membershipAccepted: 'Hvis tomten ikke allerede er registrert, sender vi en bekreftelseslenke til hovedadressen du oppga.', timeout: 'Innsendingen tok for lang tid. Prøv igjen.', checkFields: 'Forespørselen kunne ikke behandles. Kontroller feltene og prøv igjen.' },
  survey: { reload: 'Last inn undersøkelsen på nytt før du sender inn svaret.', changed: 'Spørsmålene er endret siden du åpnet skjemaet. Last inn undersøkelsen på nytt og svar på de oppdaterte spørsmålene.', allRequired: 'Alle spørsmål må besvares.', conflict: 'Svaret ble ikke lagret. Undersøkelsen eller tilgangen kan ha endret seg, eller tomten har allerede svart. Last inn undersøkelsen på nytt.', browserRejected: 'Nettleseren kunne ikke sende inn svaret sikkert. Åpne invitasjonslenken på nytt i Safari, Chrome, Edge eller Firefox og prøv igjen.', saveFailed: 'Vi klarte ikke å lagre svaret ditt. Prøv igjen om litt.' },
  map: { rateLimit: 'For mange kartoppslag. Vent litt og prøv igjen.', unavailable: 'Kartdataene er midlertidig utilgjengelige. Prøv igjen senere.' },
  cms: { missing: 'Siden finnes ikke.', unpublished: 'Siden finnes ikke eller er ikke publisert.', unavailable: 'Artikkelen er midlertidig utilgjengelig.' },
};

backend.usage = { unavailable: 'Bruksstatistikk er midlertidig utilgjengelig.' };
backend.adminMembers = { load: 'Kunne ikke hente flere medlemmer.', hRequired: 'H-nummer må fylles ut.', check: 'Kontroller medlemsopplysningene.', missing: 'Medlemmet finnes ikke lenger.', fetch: 'Kunne ikke hente medlemmet.', duplicate: 'H-nummeret er allerede i bruk.', mock: 'Mock-data kan ikke endres.', invalid: 'Kontroller at feltene har gyldige verdier.', save: 'Kunne ikke lagre medlemmet.', schema: 'Databasen mangler oppdatert skjema. Kjør npm run db:setup og prøv igjen.', delete: 'Kunne ikke slette medlemmet.', surveyMissing: 'Undersøkelsen finnes ikke.', export: 'Kunne ikke generere Excel-filen.' };
backend.adminGroups = { load: 'Kunne ikke hente gruppene.', save: 'Kunne ikke lagre gruppen. Kontroller navn og utvalg, og prøv igjen.' };
backend.adminRequests = { missing: 'Forespørselen finnes ikke lenger.', cadastral: 'Matrikkelopplysningene må avklares før godkjenning.', process: 'Forespørselen kunne ikke behandles.' };
backend.adminSurveys = { load: 'Kunne ikke hente undersøkelser.', mock: 'Mock-data kan ikke endres.', check: 'Kontroller navn, sluttdato og spørsmål.', save: 'Kunne ikke lagre undersøkelsen.', schema: 'Databasen mangler oppdatert skjema. Kjør npm run db:setup og prøv igjen.', oldId: 'Undersøkelsen har en eldre ID. Kjør npm run db:setup og prøv igjen.', missing: 'Undersøkelsen finnes ikke lenger.', missingShort: 'Undersøkelsen finnes ikke.', delete: 'Kunne ikke slette undersøkelsen.', invalidId: 'Undersøkelses-ID-en er ugyldig.', results: 'Kunne ikke hente resultatene.', export: 'Kunne ikke generere Excel-filen.', emailPermission: 'MailerSend-tokenet mangler «Suppressions: Read only». Opprett et nytt token og start serveren på nytt.', emailForbidden: 'Du har ikke tilgang til e-postutsendelse.', cannotSend: 'Undersøkelsen kan ikke sendes ut.', emailAction: 'E-posthandlingen kunne ikke fullføres.', emailRate: 'For mange e-posthandlinger. Vent ett minutt.', invalidEmailAction: 'Ugyldig e-posthandling.', emailStart: 'Kunne ikke bekrefte oppstart av e-postjobben. Ingen ny utsendelse er bekreftet. Kontroller status før du prøver igjen.' };
backend.adminCms = { login: 'Innlogging kreves.', duplicateUrl: 'URL-en er allerede i bruk. Velg en annen URL.', mock: 'CMS-et kan ikke endres i mock-modus.', check: 'Kontroller tittel, URL, kategori og tekstlengder.', missing: 'Siden finnes ikke.', missingLong: 'Siden finnes ikke lenger.', status: 'Kunne ikke endre publiseringsstatus.', attachmentMissing: 'Vedlegget finnes ikke lenger.', attachmentName: 'Skriv inn et visningsnavn på maksimalt 200 tegn.', removeAttachment: 'Kunne ikke fjerne vedlegget.', saveBeforeImage: 'Lagre siden før du laster opp et bilde.', storage: 'Fillagring er ikke konfigurert. Kjør Neon-oppsettet først.', imageType: 'Bildet må være JPG, PNG eller WebP og maksimalt 10 MB.', imageTooLarge: 'Bildet er for stort.', imageMissing: 'Bildet finnes ikke lenger.', removeImage: 'Kunne ikke fjerne bildet.', fileTooLarge: 'Filen er for stor.', tooManyAttachments: 'En side kan ha maksimalt 20 vedlegg.', unsupportedFile: 'Filtypen støttes ikke, eller filen er større enn 20 MB.', attachmentOrder: 'Kunne ikke endre rekkefølgen på vedleggene.' };
backend.adminMatrikkel = { forbidden: 'Du har ikke tilgang til matrikkelsynkronisering.', processFailed: 'Synkroniseringen stoppet på grunn av en teknisk feil.', missing: 'Kjøringen finnes ikke.', active: 'En aktiv kjøring må stoppes før den kan fjernes fra loggen.', finished: 'Kjøringen er allerede avsluttet.', change: 'Kunne ikke endre kjøringen.', status: 'Kunne ikke hente synkroniseringsstatus.', startUnconfirmed: 'Kunne ikke bekrefte oppstart. Kontroller kjørestatus før du prøver igjen.', alreadyRunning: 'En synkronisering pågår allerede.', approve: 'Kunne ikke godkjenne oppslaget.' };
backend.adminNewsletters = { load: 'Kunne ikke hente nyhetsbrevene.', rate: 'For mange forespørsler. Vent litt og prøv igjen.', start: 'Kunne ikke bekrefte oppstart. Kontroller konfigurasjonen før du prøver igjen.', conflict: 'Ingen mottakere er valgt, eller kampanjen kan ikke endres.', unavailable: 'E-posttjenesten er midlertidig utilgjengelig.', check: 'Kontroller innhold, grupper og tilgang.' };
backend.adminMembers.noSelection = 'Ingen medlemmer er valgt.';
backend.adminMembers.exportCheck = 'Kontroller eksportvalgene.';
Object.assign(backend.adminMatrikkel, { apiMissing: 'Matrikkel-API er ikke konfigurert.', invalidHNumber: 'H-nummeret har ugyldig format.', invalidSelection: 'Medlemsvalget er ugyldig.', memberMissing: 'Medlemmet finnes ikke lenger.', start: 'Kunne ikke starte synkroniseringen.' });
Object.assign(backend.adminSurveys, { emailDisabled: 'E-postsending er deaktivert.', emailConfiguration: 'MailerSend er ikke ferdig konfigurert.', emailJobConfiguration: 'Masseutsendelse må startes fra produksjonssiden, og Netlify-jobben må være konfigurert.', bulkDisabled: 'Masseutsendelse er deaktivert inntil videre.', suppressed: 'Testmottakeren er undertrykt og kan ikke motta e-post.', invalidRequest: 'Ugyldig forespørsel.', storage: 'Fillagring er ikke konfigurert. Kjør Neon-oppsettet først.', fileTooLarge: 'Filen er for stor.', tooManyAttachments: 'En undersøkelse kan ha maksimalt 20 vedlegg.', unsupportedFile: 'Filtypen støttes ikke, eller filen er større enn 20 MB.', attachmentMissing: 'Vedlegget finnes ikke lenger.', attachmentName: 'Skriv inn et visningsnavn på maksimalt 200 tegn.', removeAttachment: 'Kunne ikke fjerne vedlegget.' });
export default backend;
