const backend = {
  api: { unauthorized: 'Sign-in required.', forbidden: 'You do not have access.', invalidRequest: 'Invalid request.', invalidJson: 'Invalid JSON.', serverError: 'The request could not be completed. Please try again.', tooManyRequests: 'Too many requests. Wait a moment and try again.' },
  members: { attempts: 'Too many attempts. Wait a moment before trying again.', genericAccess: 'If the information matches the register, we will send a secure link to the registered primary email.', unavailableWait: 'The service is temporarily unavailable. Wait a moment and try again.', changes: 'Too many changes. Wait a moment and try again.', ownershipSent: 'The change of ownership was submitted for review.', emailSent: 'A confirmation link was sent to the current primary email address.', invalidAction: 'Invalid action.', updated: 'The information has been updated.', unavailable: 'The service is temporarily unavailable. Please try again later.', invalidAccess: 'Access is invalid or has expired.', ownershipPending: 'A change-of-ownership request is already pending review.', emailFlow: 'The primary email must be changed through the separate verification flow.', deliveryUnavailable: 'We cannot send confirmation to the registered address. Contact Turufjell Vel.', checkContact: 'Check the contact details.', membershipAccepted: 'If the property is not already registered, we will send a confirmation link to the primary address you provided.', timeout: 'Submission took too long. Please try again.', checkFields: 'The request could not be processed. Check the fields and try again.' },
  survey: { reload: 'Reload the survey before submitting your response.', changed: 'The questions have changed since you opened the form. Reload the survey and answer the updated questions.', allRequired: 'All questions must be answered.', conflict: 'The response was not saved. The survey or access may have changed, or the property may already have responded. Reload the survey.', saveFailed: 'We could not save your response. Please try again shortly.' },
  map: { rateLimit: 'Too many map lookups. Wait a moment and try again.', unavailable: 'Map data is temporarily unavailable. Please try again later.' },
  cms: { missing: 'The page does not exist.', unpublished: 'The page does not exist or is not published.', unavailable: 'The article is temporarily unavailable.' },
};

backend.usage = { unavailable: 'Usage statistics are temporarily unavailable.' };
backend.adminMembers = { load: 'Could not load more members.', hRequired: 'H-number is required.', check: 'Check the member details.', missing: 'The member no longer exists.', fetch: 'Could not load the member.', duplicate: 'The H-number is already in use.', mock: 'Mock data cannot be changed.', invalid: 'Check that all fields have valid values.', save: 'Could not save the member.', schema: 'The database schema is out of date. Run npm run db:setup and try again.', delete: 'Could not delete the member.', surveyMissing: 'The survey does not exist.', export: 'Could not generate the Excel file.' };
backend.adminGroups = { load: 'Could not load the groups.', save: 'Could not save the group. Check the name and selection, then try again.' };
backend.adminRequests = { missing: 'The request no longer exists.', cadastral: 'The cadastral details must be resolved before approval.', process: 'The request could not be processed.' };
backend.adminSurveys = { load: 'Could not load surveys.', mock: 'Mock data cannot be changed.', check: 'Check the name, end date and questions.', save: 'Could not save the survey.', schema: 'The database schema is out of date. Run npm run db:setup and try again.', oldId: 'The survey has a legacy ID. Run npm run db:setup and try again.', missing: 'The survey no longer exists.', missingShort: 'The survey does not exist.', delete: 'Could not delete the survey.', invalidId: 'The survey ID is invalid.', results: 'Could not load the results.', export: 'Could not generate the Excel file.', emailPermission: 'The MailerSend token lacks “Suppressions: Read only”. Create a new token and restart the server.', emailForbidden: 'You do not have access to email sending.', cannotSend: 'The survey cannot be sent.', emailAction: 'The email action could not be completed.', emailRate: 'Too many email actions. Wait one minute.', invalidEmailAction: 'Invalid email action.', emailStart: 'Could not confirm that the email job started. No new mailing has been confirmed. Check the status before trying again.' };
backend.adminCms = { login: 'Sign-in is required.', duplicateUrl: 'The URL is already in use. Select another URL.', mock: 'The CMS cannot be changed in mock mode.', check: 'Check the title, URL, category and text lengths.', missing: 'The page does not exist.', missingLong: 'The page no longer exists.', status: 'Could not change publication status.', attachmentMissing: 'The attachment no longer exists.', attachmentName: 'Enter a display name of no more than 200 characters.', removeAttachment: 'Could not remove the attachment.', saveBeforeImage: 'Save the page before uploading an image.', storage: 'File storage is not configured. Complete the Neon setup first.', imageType: 'The image must be JPG, PNG or WebP and no larger than 10 MB.', imageTooLarge: 'The image is too large.', imageMissing: 'The image no longer exists.', removeImage: 'Could not remove the image.', fileTooLarge: 'The file is too large.', tooManyAttachments: 'A page can have no more than 20 attachments.', unsupportedFile: 'The file type is unsupported or the file is larger than 20 MB.', attachmentOrder: 'Could not change the attachment order.' };
backend.adminMatrikkel = { forbidden: 'You do not have access to cadastral synchronisation.', processFailed: 'Synchronisation stopped because of a technical error.', missing: 'The run does not exist.', active: 'An active run must be stopped before it can be removed from the log.', finished: 'The run has already ended.', change: 'Could not change the run.', status: 'Could not load synchronisation status.', startUnconfirmed: 'Could not confirm startup. Check the run status before trying again.', alreadyRunning: 'A synchronisation is already in progress.', approve: 'Could not approve the lookup.' };
backend.adminNewsletters = { load: 'Could not load the newsletters.', rate: 'Too many requests. Wait a moment and try again.', start: 'Could not confirm startup. Check the configuration before trying again.', conflict: 'No recipients are selected, or the campaign cannot be changed.', unavailable: 'The email service is temporarily unavailable.', check: 'Check the content, groups and access.' };
backend.adminMembers.noSelection = 'No members are selected.';
backend.adminMembers.exportCheck = 'Check the export options.';
Object.assign(backend.adminMatrikkel, { apiMissing: 'The cadastral API is not configured.', invalidHNumber: 'The H-number format is invalid.', invalidSelection: 'The member selection is invalid.', memberMissing: 'The member no longer exists.', start: 'Could not start synchronisation.' });
Object.assign(backend.adminSurveys, { emailDisabled: 'Email sending is disabled.', emailConfiguration: 'MailerSend is not fully configured.', emailJobConfiguration: 'Bulk mailing must be started from the production site, and the Netlify job must be configured.', bulkDisabled: 'Bulk mailing is currently disabled.', suppressed: 'The test recipient is suppressed and cannot receive email.', invalidRequest: 'Invalid request.', storage: 'File storage is not configured. Complete the Neon setup first.', fileTooLarge: 'The file is too large.', tooManyAttachments: 'A survey can have no more than 20 attachments.', unsupportedFile: 'The file type is unsupported or the file is larger than 20 MB.', attachmentMissing: 'The attachment no longer exists.', attachmentName: 'Enter a display name of no more than 200 characters.', removeAttachment: 'Could not remove the attachment.' });
export default backend;
